INSERT INTO papers (year,session,subject,title,description,url) VALUES
(2022,'I','Mathematics','NDA 2022-I Mathematics','Official UPSC archive • 33.93 MB','https://www.upsc.gov.in/examinations/previous-question-papers/archives'),
(2022,'I','GAT','NDA 2022-I General Ability Test','Official UPSC archive • 26.15 MB','https://www.upsc.gov.in/examinations/previous-question-papers/archives'),
(2022,'II','Mathematics','NDA 2022-II Mathematics','Official UPSC archive • 29.99 MB','https://www.upsc.gov.in/examinations/previous-question-papers/archives'),
(2022,'II','GAT','NDA 2022-II General Ability Test','Official UPSC archive • 28.39 MB','https://www.upsc.gov.in/examinations/previous-question-papers/archives'),
(2021,'I','Mathematics','NDA 2021-I Mathematics','Official UPSC archive • 5.34 MB','https://www.upsc.gov.in/examinations/previous-question-papers/archives'),
(2021,'I','GAT','NDA 2021-I General Ability Test','Official UPSC archive • 5.3 MB','https://www.upsc.gov.in/examinations/previous-question-papers/archives'),
(2021,'II','Mathematics','NDA 2021-II Mathematics','Official UPSC archive • 26.56 MB','https://www.upsc.gov.in/examinations/previous-question-papers/archives'),
(2021,'II','GAT','NDA 2021-II General Ability Test','Official UPSC archive • 23.72 MB','https://www.upsc.gov.in/examinations/previous-question-papers/archives'),
(2020,'I & II','Mathematics','NDA 2020 Mathematics','Official UPSC archive','https://www.upsc.gov.in/examinations/previous-question-papers/archives'),
(2020,'I & II','GAT','NDA 2020 General Ability Test','Official UPSC archive','https://www.upsc.gov.in/examinations/previous-question-papers/archives'),
(2019,'I','Mathematics','NDA 2019-I Mathematics','Official UPSC archive','https://www.upsc.gov.in/examinations/previous-question-papers/archives'),
(2019,'I','GAT','NDA 2019-I General Ability Test','Official UPSC archive','https://www.upsc.gov.in/examinations/previous-question-papers/archives'),
(2019,'II','Mathematics','NDA 2019-II Mathematics','Official UPSC archive','https://www.upsc.gov.in/examinations/previous-question-papers/archives'),
(2019,'II','GAT','NDA 2019-II General Ability Test','Official UPSC archive','https://www.upsc.gov.in/examinations/previous-question-papers/archives'),
(2018,'I','Mathematics','NDA 2018-I Mathematics','Official UPSC archive','https://www.upsc.gov.in/examinations/previous-question-papers/archives'),
(2018,'I','GAT','NDA 2018-I General Ability Test','Official UPSC archive','https://www.upsc.gov.in/examinations/previous-question-papers/archives'),
(2018,'II','Mathematics','NDA 2018-II Mathematics','Official UPSC archive','https://www.upsc.gov.in/examinations/previous-question-papers/archives'),
(2018,'II','GAT','NDA 2018-II General Ability Test','Official UPSC archive','https://www.upsc.gov.in/examinations/previous-question-papers/archives'),
(2017,'I','Mathematics','NDA 2017-I Mathematics','Official UPSC archive','https://www.upsc.gov.in/examinations/previous-question-papers/archives'),
(2017,'I','GAT','NDA 2017-I General Ability Test','Official UPSC archive','https://www.upsc.gov.in/examinations/previous-question-papers/archives'),
(2017,'II','Mathematics','NDA 2017-II Mathematics','Official UPSC archive','https://www.upsc.gov.in/examinations/previous-question-papers/archives'),
(2017,'II','GAT','NDA 2017-II General Ability Test','Official UPSC archive','https://www.upsc.gov.in/examinations/previous-question-papers/archives'),
(2016,'I','Mathematics','NDA 2016-I Mathematics','Official UPSC archive','https://www.upsc.gov.in/examinations/previous-question-papers/archives'),
(2016,'I','GAT','NDA 2016-I General Ability Test','Official UPSC archive','https://www.upsc.gov.in/examinations/previous-question-papers/archives'),
(2016,'II','Mathematics','NDA 2016-II Mathematics','Official UPSC archive','https://www.upsc.gov.in/examinations/previous-question-papers/archives'),
(2016,'II','GAT','NDA 2016-II General Ability Test','Official UPSC archive','https://www.upsc.gov.in/examinations/previous-question-papers/archives')
ON CONFLICT DO NOTHING